# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import pyqtgraph as pg
import numpy as np
pg.setConfigOption('background', (240,240,240))
pg.setConfigOption('foreground', 'k')
pen = pg.mkPen(color=(255, 0, 255))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphWidget = PlotWidget(parent=self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(330, 100, 351, 231))
        self.graphWidget.setObjectName("graphWidget")

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 170, 91, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("off.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget, 
                                                pressed=lambda:self.press(), released=lambda:self.release())
        self.pushButton.setGeometry(QtCore.QRect(190, 290, 75, 24))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuRonny_Landsverk = QtWidgets.QMenu(parent=self.menubar)
        self.menuRonny_Landsverk.setObjectName("menuRonny_Landsverk")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuRonny_Landsverk.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def press(self):
        self.label.setPixmap(QtGui.QPixmap('on.png'))
    def release(self):
        self.label.setPixmap(QtGui.QPixmap('off.png'))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Press-me"))
        self.menuRonny_Landsverk.setTitle(_translate("MainWindow", "Ronny Landsverk"))
    
    def plot(self, x, y):
        self.graphWidget.plot(x,y,pen=pen)


class myApp(QtWidgets.QMainWindow):
    def __init__(self):
        super(myApp, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.counter = 0
        self.x = []
        self.y = []
        self.timer = QtCore.QTimer(self)
        self.timer.timeout.connect(self.increment_counter)
        self.timer.start(20)

    def increment_counter(self):
        self.counter += 1
        self.x.append(self.counter)
        self.y.append(np.cos(self.counter/10))
        if self.counter > 100:
            self.ui.graphWidget.clear()
            self.ui.plot(self.x[-100:], self.y[-100:])
        else:
            self.ui.plot(self.x, self.y)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = myApp()
    MainWindow.show()
    sys.exit(app.exec())

